equivalencies = {'CA01': ('ara', 'Diari Ara'),
                 'CA02': ('elperiodicocat', 'El Periodico de Catalunya'),
                 'CA03': ('diarigirona', 'Diari de Girona'),
                 'CA04': ('regio7', 'Regio 7'),
                 'CA05': ('naciodigital', 'Nacio Digital'),
                 'CA06': ('diarilaveu', 'Diari La Veu'),
                 'CA07': ('elpuntavui', 'El Punt Avui'),
                 'CA08': ('eltemps', 'El Temps'),
                 'CA09': ('vilaweb', 'VilaWeb'),
                 'ES01': ('elpais', 'El Pais'),
                 'ES02': ('lasprovincias', 'Las Provincias'),
                 'ES03': ('diariodemallorca', 'Diario de Mallorca'),
                 'ES04': ('abc', 'ABC'),
                 'ES05': ('elespanol', 'El Español'),
                 'ES06': ('eldiario', 'El Diario'),
                 'ES07': ('publico', 'Publico'),
                 'ES08': ('lavanguardia', 'La Vanguardia'),
                 'ES09': ('levante', 'Levante'),
                 'ES10': ('elperiodicoes', 'El Periodico de Catalunya'),
                 'ES11': ('20minutos', '20 Minutos'),
                 'ES12': ('elperdearagon', 'El Periodico de Aragon'),
                 'ES13': ('larazon', 'La Razon'),
                 'ES14': ('elmundo', 'El Mundo'),
                 'ES15': ('efe', 'Agencia EFE'),
                 'ES16': ('elindependiente', 'El Independiente'),
                 'ES17': ('nodo50', 'Nodo 50'),
                 'ES18': ('eleconomista', 'El Economista'),
                 'ES19': ('europapress', 'Europa Press'),
                 'ES20': ('ultimahora', 'Ultima Hora'),
                 'ES21': ('expansion', 'Expansion')}